``` Before running this notebook, look at all commented-out function calls and determine if you actually need to call them or not. The following notebook will alter the contents (drop and add rows and cols). The function uses randomization, so it may or may not mess up with the previous accuracy of the model.```

In [124]:
import pandas as pd 
import numpy as np
import os

In [125]:
curr_dir = os.getcwd()

parent_dir = os.path.dirname(curr_dir) # gtes the name of the parent directory

singles_net_stats_path = os.path.join(parent_dir, 'stats', 'singles_net_stats', 'singles_net_stats2.csv')
df = pd.read_csv(singles_net_stats_path)

In [126]:
# drop unnamed cols
def drop_unnamed(df):
    df = df.loc[:, ~df.columns.str.startswith('Unnamed')]
    return df

In [127]:
df = drop_unnamed(df)
# drop all NaN
df = df.dropna(axis=0, how='any', subset=[
    'winner_ht',
    'loser_ht',
    'winner_age',
    'loser_age',
    'score',
    'minutes',
    'w_df',
    'w_svpt',
    'w_1stIn',
    'w_2ndWon',
    'w_bpSaved',
    'w_bpFaced',
    'l_df',
    'l_svpt',
    'l_1stIn',
    'l_2ndWon',
    'l_bpSaved',
    'l_bpFaced',
    'rank_points_diff',
    'winner_rank',
    'loser_rank'
])
df

,tourney_name,surface,draw_size,tourney_level,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,...,winner_hand_n,winner_ioc_n,loser_hand_n,loser_ioc_n,round_n,winner_name_n,loser_name_n,winner_entry_n,loser_entry_n,rank_points_diff
86683,Auckland,Hard,32.0,A,1.0,NaN,Emilio Sanchez,R,180.0,ESP,...,2,36,2,64,6,1109,5873,10,11,1028.0
86684,Auckland,Hard,32.0,A,NaN,Q,Malivai Washington,R,180.0,USA,...,2,124,2,94,6,2603,6583,5,10,257.0
86685,Auckland,Hard,32.0,A,NaN,NaN,Jean Philippe Fleurian,R,185.0,FRA,...,2,39,2,94,6,1921,959,10,10,352.0
86686,Auckland,Hard,32.0,A,NaN,NaN,Eric Jelen,R,180.0,GER,...,2,43,1,63,6,1133,2477,10,11,19.0
86687,Auckland,Hard,32.0,A,NaN,Q,Chuck Adams,R,185.0,USA,...,2,124,2,5,6,736,5916,5,11,-734.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194984,Davis Cup WG2 PO: TOG vs INA,Hard,4.0,D,NaN,NaN,Fitriadi M Rifqi,R,175.0,INA,...,2,51,2,127,8,1255,6817,10,11,40.0
194986,Davis Cup WG2 PO: TUN vs CRC,Hard,4.0,D,NaN,NaN,Moez Echargui,R,178.0,TUN,...,2,117,2,30,8,2980,3364,10,11,187.0
194988,Davis Cup WG2 PO: URU vs MDA,Clay,4.0,D,NaN,NaN,Franco Roncadelli,L,185.0,URU,...,1,123,2,82,8,1294,2963,10,11,21.0
194990,Davis Cup WG2 PO: URU vs MDA,Clay,4.0,D,NaN,NaN,Radu Albot,R,175.0,MDA,...,2,74,1,136,8,3411,2201,10,11,434.0
194994,Davis Cup WG2 PO: VIE vs RSA,Hard,4.0,D,NaN,NaN,Nam Hoang Ly,R,175.0,VIE,...,2,127,2,109,8,3021,4085,10,11,-42.0

In [128]:
import random

In [129]:
def add_binary_col(df):
    winner_p1 = []
    p1 = []
    p2 = []

    for index, row in df.iterrows():
        if random.random() > 0.5:
            winner_p1.append(1)
            p1.append(row['winner_name_n'])
            p2.append(row['loser_name_n'])
        else:
            winner_p1.append(0)
            p1.append(row['loser_name_n'])
            p2.append(row['winner_name_n'])

    df['winner_p1'] = winner_p1
    df['p2'] = p2
    df['p1'] = p1

    return df

In [130]:
# df = add_binary_col(df)
df

,tourney_name,surface,draw_size,tourney_level,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,...,loser_ioc_n,round_n,winner_name_n,loser_name_n,winner_entry_n,loser_entry_n,rank_points_diff,winner_p1,p2,p1
86683,Auckland,Hard,32.0,A,1.0,NaN,Emilio Sanchez,R,180.0,ESP,...,64,6,1109,5873,10,11,1028.0,1,5873,1109
86684,Auckland,Hard,32.0,A,NaN,Q,Malivai Washington,R,180.0,USA,...,94,6,2603,6583,5,10,257.0,1,6583,2603
86685,Auckland,Hard,32.0,A,NaN,NaN,Jean Philippe Fleurian,R,185.0,FRA,...,94,6,1921,959,10,10,352.0,1,959,1921
86686,Auckland,Hard,32.0,A,NaN,NaN,Eric Jelen,R,180.0,GER,...,63,6,1133,2477,10,11,19.0,1,2477,1133
86687,Auckland,Hard,32.0,A,NaN,Q,Chuck Adams,R,185.0,USA,...,5,6,736,5916,5,11,-734.0,1,5916,736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194984,Davis Cup WG2 PO: TOG vs INA,Hard,4.0,D,NaN,NaN,Fitriadi M Rifqi,R,175.0,INA,...,127,8,1255,6817,10,11,40.0,1,6817,1255
194986,Davis Cup WG2 PO: TUN vs CRC,Hard,4.0,D,NaN,NaN,Moez Echargui,R,178.0,TUN,...,30,8,2980,3364,10,11,187.0,1,3364,2980
194988,Davis Cup WG2 PO: URU vs MDA,Clay,4.0,D,NaN,NaN,Franco Roncadelli,L,185.0,URU,...,82,8,1294,2963,10,11,21.0,0,1294,2963
194990,Davis Cup WG2 PO: URU vs MDA,Clay,4.0,D,NaN,NaN,Radu Albot,R,175.0,MDA,...,136,8,3411,2201,10,11,434.0,1,2201,3411
194994,Davis Cup WG2 PO: VIE vs RSA,Hard,4.0,D,NaN,NaN,Nam Hoang Ly,R,175.0,VIE,...,109,8,3021,4085,10,11,-42.0,0,3021,4085

In [131]:
def compute_diffence_stats(df):
    ht_p1 = []
    age_p1 = []
    ace_p1 = []
    df_p1 = []
    svpt_p1 = []
    first_serve_p1 = []
    first_serve_won_p1 = []
    second_serve_won_p1 = []
    svgm_p1 = []
    bpsaved_p1 = []
    bpfaced_p1 = []

    ht_p2 = []
    age_p2 = []
    ace_p2 = []
    df_p2 = []
    svpt_p2 = []
    first_serve_p2 = []
    first_serve_won_p2 = []
    second_serve_won_p2 = []
    svgm_p2 = []
    bpsaved_p2 = []
    bpfaced_p2 = []

    for index, row in df.iterrows():
        if row['winner_name_n'] == row['p1']:
            # p1 is winner
            ht_p1.append(row['winner_ht'])
            age_p1.append(row['winner_age'])
            ace_p1.append(row['w_ace'])
            df_p1.append(row['w_df'])
            svpt_p1.append(row['w_svpt'])
            first_serve_p1.append(row['w_1stIn'])
            first_serve_won_p1.append(row['w_1stWon'])
            second_serve_won_p1.append(row['w_2ndWon'])
            svgm_p1.append(row['w_SvGms'])
            bpfaced_p1.append(row['w_bpFaced'])
            bpsaved_p1.append(row['w_bpSaved'])

            # p2 is loser
            ht_p2.append(row['loser_ht'])
            age_p2.append(row['loser_age'])
            ace_p2.append(row['l_ace'])
            df_p2.append(row['l_df'])
            svpt_p2.append(row['l_svpt'])
            first_serve_p2.append(row['l_1stIn'])
            first_serve_won_p2.append(row['l_1stWon'])
            second_serve_won_p2.append(row['l_2ndWon'])
            svgm_p2.append(row['l_SvGms'])
            bpfaced_p2.append(row['l_bpFaced'])
            bpsaved_p2.append(row['l_bpSaved'])
        else:
            # p1 is loser
            ht_p1.append(row['loser_ht'])
            age_p1.append(row['loser_age'])
            ace_p1.append(row['l_ace'])
            df_p1.append(row['l_df'])
            svpt_p1.append(row['l_svpt'])
            first_serve_p1.append(row['l_1stIn'])
            first_serve_won_p1.append(row['l_1stWon'])
            second_serve_won_p1.append(row['l_2ndWon'])
            svgm_p1.append(row['l_SvGms'])
            bpfaced_p1.append(row['l_bpFaced'])
            bpsaved_p1.append(row['l_bpSaved'])

            # p2 is winner
            ht_p2.append(row['winner_ht'])
            age_p2.append(row['winner_age'])
            ace_p2.append(row['w_ace'])
            df_p2.append(row['w_df'])
            svpt_p2.append(row['w_svpt'])
            first_serve_p2.append(row['w_1stIn'])
            first_serve_won_p2.append(row['w_1stWon'])
            second_serve_won_p2.append(row['w_2ndWon'])
            svgm_p2.append(row['w_SvGms'])
            bpfaced_p2.append(row['w_bpFaced'])
            bpsaved_p2.append(row['w_bpSaved'])

    # compute diffence stats
    df['diff_ht'] = pd.Series(ht_p1) - pd.Series(ht_p2)
    df['diff_age'] = pd.Series(age_p1) - pd.Series(age_p2)
    df['diff_ace'] = pd.Series(ace_p1) - pd.Series(ace_p2)
    df['diff_df'] = pd.Series(df_p1) - pd.Series(df_p2)
    df['diff_svpt'] = pd.Series(svpt_p1) - pd.Series(svpt_p2)
    df['diff_1stIn'] = pd.Series(first_serve_p1) - pd.Series(first_serve_p2)
    df['diff_1stWon'] = pd.Series(first_serve_won_p1) - pd.Series(first_serve_won_p2)
    df['diff_2ndWon'] = pd.Series(second_serve_won_p1) - pd.Series(second_serve_won_p2)
    df['diff_SvGms'] = pd.Series(svgm_p1) - pd.Series(svgm_p2)
    df['diff_bpFaced'] = pd.Series(bpfaced_p1) - pd.Series(bpfaced_p2)
    df['diff_bpSaved'] = pd.Series(bpsaved_p1) - pd.Series(bpsaved_p2)

    return df

In [132]:
df = compute_diffence_stats(df)
df

,tourney_name,surface,draw_size,tourney_level,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,...,diff_age,diff_ace,diff_df,diff_svpt,diff_1stIn,diff_1stWon,diff_2ndWon,diff_SvGms,diff_bpFaced,diff_bpSaved
86683,Auckland,Hard,32.0,A,1.0,NaN,Emilio Sanchez,R,180.0,ESP,...,-2.7,0.0,-1.0,0.0,2.0,1.0,1.0,1.0,2.0,3.0
86684,Auckland,Hard,32.0,A,NaN,Q,Malivai Washington,R,180.0,USA,...,-10.0,0.0,-1.0,-3.0,-10.0,-1.0,9.0,1.0,-6.0,-3.0
86685,Auckland,Hard,32.0,A,NaN,NaN,Jean Philippe Fleurian,R,185.0,FRA,...,10.5,1.0,-1.0,0.0,9.0,8.0,-4.0,1.0,1.0,2.0
86686,Auckland,Hard,32.0,A,NaN,NaN,Eric Jelen,R,180.0,GER,...,2.7,2.0,2.0,11.0,8.0,0.0,-4.0,0.0,8.0,4.0
86687,Auckland,Hard,32.0,A,NaN,Q,Chuck Adams,R,185.0,USA,...,1.0,-11.0,3.0,14.0,10.0,-5.0,3.0,0.0,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194984,Davis Cup WG2 PO: TOG vs INA,Hard,4.0,D,NaN,NaN,Fitriadi M Rifqi,R,175.0,INA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194986,Davis Cup WG2 PO: TUN vs CRC,Hard,4.0,D,NaN,NaN,Moez Echargui,R,178.0,TUN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194988,Davis Cup WG2 PO: URU vs MDA,Clay,4.0,D,NaN,NaN,Franco Roncadelli,L,185.0,URU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194990,Davis Cup WG2 PO: URU vs MDA,Clay,4.0,D,NaN,NaN,Radu Albot,R,175.0,MDA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194994,Davis Cup WG2 PO: VIE vs RSA,Hard,4.0,D,NaN,NaN,Nam Hoang Ly,R,175.0,VIE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [134]:
df = df.dropna(axis=0, how='any', subset=[
    'winner_ht',
    'loser_ht',
    'winner_age',
    'loser_age',
    'score',
    'minutes',
    'w_df',
    'w_svpt',
    'w_1stIn',
    'w_2ndWon',
    'w_bpSaved',
    'w_bpFaced',
    'l_df',
    'l_svpt',
    'l_1stIn',
    'l_2ndWon',
    'l_bpSaved',
    'l_bpFaced',
    'rank_points_diff',
    'winner_rank',
    'loser_rank',
    'diff_ht',
    'diff_age',
    'diff_age',
    'diff_df',
    'diff_svpt',
    'diff_1stIn',
    'diff_1stWon',
    'diff_2ndWon',
    'diff_SvGms',
    'diff_bpFaced',
    'diff_bpSaved'
])
df

,tourney_name,surface,draw_size,tourney_level,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,...,diff_age,diff_ace,diff_df,diff_svpt,diff_1stIn,diff_1stWon,diff_2ndWon,diff_SvGms,diff_bpFaced,diff_bpSaved
86683,Auckland,Hard,32.0,A,1.0,NaN,Emilio Sanchez,R,180.0,ESP,...,-2.7,0.0,-1.0,0.0,2.0,1.0,1.0,1.0,2.0,3.0
86684,Auckland,Hard,32.0,A,NaN,Q,Malivai Washington,R,180.0,USA,...,-10.0,0.0,-1.0,-3.0,-10.0,-1.0,9.0,1.0,-6.0,-3.0
86685,Auckland,Hard,32.0,A,NaN,NaN,Jean Philippe Fleurian,R,185.0,FRA,...,10.5,1.0,-1.0,0.0,9.0,8.0,-4.0,1.0,1.0,2.0
86686,Auckland,Hard,32.0,A,NaN,NaN,Eric Jelen,R,180.0,GER,...,2.7,2.0,2.0,11.0,8.0,0.0,-4.0,0.0,8.0,4.0
86687,Auckland,Hard,32.0,A,NaN,Q,Chuck Adams,R,185.0,USA,...,1.0,-11.0,3.0,14.0,10.0,-5.0,3.0,0.0,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92399,Wimbledon,Grass,128.0,G,12.0,NaN,Andre Agassi,R,180.0,USA,...,-3.2,-1.0,1.0,2.0,-3.0,6.0,6.0,1.0,-6.0,-3.0
92400,Wimbledon,Grass,128.0,G,NaN,NaN,Derrick Rostagno,R,185.0,USA,...,2.2,1.0,0.0,7.0,5.0,13.0,2.0,1.0,-1.0,2.0
92401,Wimbledon,Grass,128.0,G,NaN,Q,Christian Saceanu,R,190.0,GER,...,-2.1,-1.0,3.0,18.0,2.0,-7.0,5.0,0.0,7.0,3.0
92402,Wimbledon,Grass,128.0,G,NaN,NaN,Jakob Hlasek,R,188.0,SUI,...,10.3,1.0,0.0,-32.0,-36.0,-14.0,8.0,0.0,-7.0,-3.0
92403,Wimbledon,Grass,128.0,G,5.0,NaN,Pete Sampras,R,185.0,USA,...,0.4,5.0,2.0,2.0,-10.0,-9.0,4.0,0.0,4.0,3.0

In [136]:
df = df.drop(['winner_entry', 'loser_entry'], axis='columns')
df

,tourney_name,surface,draw_size,tourney_level,winner_seed,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,...,diff_age,diff_ace,diff_df,diff_svpt,diff_1stIn,diff_1stWon,diff_2ndWon,diff_SvGms,diff_bpFaced,diff_bpSaved
86683,Auckland,Hard,32.0,A,1.0,Emilio Sanchez,R,180.0,ESP,25.6,...,-2.7,0.0,-1.0,0.0,2.0,1.0,1.0,1.0,2.0,3.0
86684,Auckland,Hard,32.0,A,NaN,Malivai Washington,R,180.0,USA,21.5,...,-10.0,0.0,-1.0,-3.0,-10.0,-1.0,9.0,1.0,-6.0,-3.0
86685,Auckland,Hard,32.0,A,NaN,Jean Philippe Fleurian,R,185.0,FRA,25.3,...,10.5,1.0,-1.0,0.0,9.0,8.0,-4.0,1.0,1.0,2.0
86686,Auckland,Hard,32.0,A,NaN,Eric Jelen,R,180.0,GER,25.8,...,2.7,2.0,2.0,11.0,8.0,0.0,-4.0,0.0,8.0,4.0
86687,Auckland,Hard,32.0,A,NaN,Chuck Adams,R,185.0,USA,19.7,...,1.0,-11.0,3.0,14.0,10.0,-5.0,3.0,0.0,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92399,Wimbledon,Grass,128.0,G,12.0,Andre Agassi,R,180.0,USA,22.1,...,-3.2,-1.0,1.0,2.0,-3.0,6.0,6.0,1.0,-6.0,-3.0
92400,Wimbledon,Grass,128.0,G,NaN,Derrick Rostagno,R,185.0,USA,26.6,...,2.2,1.0,0.0,7.0,5.0,13.0,2.0,1.0,-1.0,2.0
92401,Wimbledon,Grass,128.0,G,NaN,Christian Saceanu,R,190.0,GER,23.9,...,-2.1,-1.0,3.0,18.0,2.0,-7.0,5.0,0.0,7.0,3.0
92402,Wimbledon,Grass,128.0,G,NaN,Jakob Hlasek,R,188.0,SUI,27.6,...,10.3,1.0,0.0,-32.0,-36.0,-14.0,8.0,0.0,-7.0,-3.0
92403,Wimbledon,Grass,128.0,G,5.0,Pete Sampras,R,185.0,USA,20.8,...,0.4,5.0,2.0,2.0,-10.0,-9.0,4.0,0.0,4.0,3.0

In [137]:
df.to_csv(singles_net_stats_path)